### ISSUE TITLE
Fixed segfault with now non-working -f option.

### ISSUE THREAD

**Issue by gknauf** [xorg62/tty-clock#1]
<pre><code>From 73584bd10bdcdf358c2a8ceba76048763ee8b378 Mon Sep 17 00:00:00 2001
From: Guenter Knauf <lists@gknw.net>
Date: Thu, 4 Nov 2010 10:37:18 +0100
Subject: [PATCH 1/3] Fixed segfault with now non-working -f option.

The commit to add the -d option broke getopt for -f taking an argument.

---
 ttyclock.c |    2 +-
 1 files changed, 1 insertions(+), 1 deletions(-)

diff --git a/ttyclock.c b/ttyclock.c
index 8fa2306..3a7122c 100644
--- a/ttyclock.c
+++ b/ttyclock.c
@@ -420,7 +420,7 @@ main(int argc, char **argv)
      /* Default delay */
      ttyclock->option.delay = 40000000; /* 25FPS */
 
-     while ((c = getopt(argc, argv, "tvsrcihfd:C:")) != -1)
+     while ((c = getopt(argc, argv, "tvsrcihf:d:C:")) != -1)
      {
           switch(c)
           {
-- 
1.7.2.2
</code></pre>

**Comment by livibetter** [comment]
@xorg62 @gknauf close?

**Comment by anarcat** [comment]
this was fixed in 85f41f16a1c2a5033c0722219f32f09430c5e9ed
