### ISSUE TITLE
Why is this described as "analog clock in ncurses" when it shows a digital clock?

### ISSUE THREAD

**Issue by Wuodan** [xorg62/tty-clock#12]
Hi

As the title says:
Why is this described as "analog clock in ncurses" when it shows a digital clock?

Thanks for adding the Makefile patch from hasufell so awesome quickly!
And for writting tty-clock of course.
Btw - I'm packaging tty-clock for Gentoo (sunrise overlay).

Regards
Wuodan

**Comment by anarcat** [comment]
true that. i am only a contributor here and cannot change the summary, @xorg62 would need to do that...

**Comment by anarcat** [comment]
i believe that `analog` is gone from the title
