### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by mistydemeo** [xorg62/tty-clock#18]
We've had a request to include this in the [homebrew](https://github.com/mxcl/homebrew/) package manager, but we need a stable release to include it. Would you be able to tag a release? Thanks!

(See mxcl/homebrew#23163)

**Comment by anarcat** [comment]
this issue can be closed.

**Comment by anarcat** [comment]
i was granted access to the repository, see #21 for updates which will come real soon now.
