### ISSUE TITLE
Changed default date format.

### ISSUE THREAD

**Issue by gknauf** [xorg62/tty-clock#2]
<pre><code>From 90c9ed5f001fc439ee05e45b06eaa4adc51d4658 Mon Sep 17 00:00:00 2001
From: Guenter Knauf <lists@gknw.net>
Date: Thu, 4 Nov 2010 10:41:53 +0100
Subject: [PATCH 2/3] Changed default date format.

In order to avoid mixing up day and month its better to use %F
(the ISO 8601 date format) to be more international understandable.

---
 ttyclock.c |    2 +-
 1 files changed, 1 insertions(+), 1 deletions(-)

diff --git a/ttyclock.c b/ttyclock.c
index 3a7122c..19a9d27 100644
--- a/ttyclock.c
+++ b/ttyclock.c
@@ -414,7 +414,7 @@ main(int argc, char **argv)
      /* Date format */
      ttyclock->option.format = malloc(sizeof(char) * 100);
      /* Default date format */
-     strncpy(ttyclock->option.format, "%d/%m/%Y", 100);
+     strncpy(ttyclock->option.format, "%F", 100);
      /* Default color */
      ttyclock->option.color = COLOR_GREEN; /* COLOR_GREEN = 2 */
      /* Default delay */
-- 
1.7.2.2
</code></pre>

**Comment by livibetter** [comment]
@xorg62 @gknauf this was done in 6607fc1a:[L503][] (2011-08-16), this can be closed. Although I think `%x` would be a better option, even personally I prefer ISO 8601 format, from `strftime(3)`:

> The preferred date representation for the current locale without the time.

[L503]: https://github.com/xorg62/tty-clock/commit/6607fc1a634769e1aa3e011a232ee39e4be4f0ed#diff-5e8d80915a9af64f58544577140d1092R503

**Comment by anarcat** [comment]
feel free to change the format by submitting a PR :)
