### ISSUE TITLE
-T option and cron's lack of tty

### ISSUE THREAD

**Issue by rabreu** [xorg62/tty-clock#20]
Does tty-clock really require a tty when using the -T option?

I have the following line on a cron script:

```
tty-clock -S -c -t -d 3 -T /dev/tty1
```

And it doesn't work because cron doesn't have a tty, but it's not really required because I'm sending it to /dev/tty1.

Tell me if I'm wrong...

**Comment by ammongit** [comment]
This is because ncurses expects a `TERM` environment variable to properly initialize the terminal. Try changing the cron line to:

```
TERM=xterm tty-clock -S -c -t -d 3 -T /dev/tty1
```

**Comment by anarcat** [comment]
not sure there's anything to do here - reopen if you think of anything else.
