### ISSUE TITLE
Undefined Symbol(s)?

### ISSUE THREAD

**Issue by ghost** [xorg62/tty-clock#27]
➜  tty-clock git:(master) make
build ttyclock.c
CC   ttyclock.c
Undefined symbols for architecture x86_64:
  "_COLS", referenced from:
      _set_center in ttyclock-bc2903.o
      _clock_rebound in ttyclock-bc2903.o
      _set_second in ttyclock-bc2903.o
      _key_event in ttyclock-bc2903.o
  "_LINES", referenced from:
      _set_center in ttyclock-bc2903.o
      _clock_rebound in ttyclock-bc2903.o
      _key_event in ttyclock-bc2903.o
  "_cbreak", referenced from:
      _init in ttyclock-bc2903.o
  "_clearok", referenced from:
      _init in ttyclock-bc2903.o
  "_curs_set", referenced from:
      _init in ttyclock-bc2903.o
  "_delscreen", referenced from:
      _cleanup in ttyclock-bc2903.o
  "_endwin", referenced from:
      _signal_handler in ttyclock-bc2903.o
      _main in ttyclock-bc2903.o
  "_init_pair", referenced from:
      _init in ttyclock-bc2903.o
      _key_event in ttyclock-bc2903.o
  "_initscr", referenced from:
      _init in ttyclock-bc2903.o
  "_keypad", referenced from:
      _init in ttyclock-bc2903.o
  "_mvwin", referenced from:
      _clock_move in ttyclock-bc2903.o
  "_mvwprintw", referenced from:
      _draw_clock in ttyclock-bc2903.o
  "_newterm", referenced from:
      _init in ttyclock-bc2903.o
  "_newwin", referenced from:
      _init in ttyclock-bc2903.o
  "_nodelay", referenced from:
      _init in ttyclock-bc2903.o
  "_noecho", referenced from:
      _init in ttyclock-bc2903.o
  "_set_term", referenced from:
      _init in ttyclock-bc2903.o
  "_start_color", referenced from:
      _init in ttyclock-bc2903.o
  "_stdscr", referenced from:
      _init in ttyclock-bc2903.o
      _key_event in ttyclock-bc2903.o
      _main in ttyclock-bc2903.o
  "_use_default_colors", referenced from:
      _init in ttyclock-bc2903.o
  "_waddch", referenced from:
      _draw_number in ttyclock-bc2903.o
  "_waddnstr", referenced from:
      _draw_clock in ttyclock-bc2903.o
  "_wattr_off", referenced from:
      _draw_number in ttyclock-bc2903.o
      _draw_clock in ttyclock-bc2903.o
  "_wattr_on", referenced from:
      _init in ttyclock-bc2903.o
      _draw_number in ttyclock-bc2903.o
      _draw_clock in ttyclock-bc2903.o
      _main in ttyclock-bc2903.o
  "_wbkgdset", referenced from:
      _draw_number in ttyclock-bc2903.o
      _draw_clock in ttyclock-bc2903.o
      _clock_move in ttyclock-bc2903.o
      _set_box in ttyclock-bc2903.o
  "_wborder", referenced from:
      _init in ttyclock-bc2903.o
      _clock_move in ttyclock-bc2903.o
      _set_box in ttyclock-bc2903.o
  "_wclear", referenced from:
      _init in ttyclock-bc2903.o
  "_werase", referenced from:
      _clock_move in ttyclock-bc2903.o
  "_wgetch", referenced from:
      _key_event in ttyclock-bc2903.o
  "_wmove", referenced from:
      _draw_number in ttyclock-bc2903.o
      _draw_clock in ttyclock-bc2903.o
  "_wrefresh", referenced from:
      _init in ttyclock-bc2903.o
      _draw_number in ttyclock-bc2903.o
      _draw_clock in ttyclock-bc2903.o
      _clock_move in ttyclock-bc2903.o
      _set_box in ttyclock-bc2903.o
  "_wresize", referenced from:
      _clock_move in ttyclock-bc2903.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: **\* [tty-clock] Error 1

On OS X in iTerm2. I'm not very advanced so this may be a simple dependency that I'm missing, but help pointing me in the right direction here would be appreciated.

**Comment by soramichi** [comment]
COLS and LINES are special variables defined in the ncurses library,
and you must install it before building tty-clock.
(I have no idea how to do it with OS X though, since I've never used a Mac machine.)

**Comment by VanAxe** [comment]
Replacing all the smart if section in the makefile with the code below will allow to the program to build on OSX provided you've tapped ncurses6 with homebrew.

```
CFLAGS ?= -Wall -g -D_DARWIN_C_SOURCE -I/usr/local/Cellar/ncurses/6.0/include
LDFLAGS ?= -L/usr/local/Cellar/ncurses/6.0/lib -lncursesw
```

Someone better than me at making makefiles can probably figure this out.

**Comment by thejmazz** [comment]
👍 Cheers, I just had to change `6.0` to `6.0_1`

**Comment by anarcat** [comment]
some cleanups of the makefile were done recently, can you try this again? see 48707576f3858df0b9167cc7fd37b282c85b3641 and previous.
