### ISSUE TITLE
will not 'make'. with errors. new ncurses?

### ISSUE THREAD

**Issue by ghost** [xorg62/tty-clock#31]
[dave@manjaro tty-clock-master :) ]$ make
build ttyclock.c
CC   ttyclock.c
/tmp/ccky1p0y.o: In function `init':
ttyclock.c:(.text+0xac): undefined reference to`newterm'
ttyclock.c:(.text+0xec): undefined reference to `set_term'
ttyclock.c:(.text+0xf3): undefined reference to`initscr'
ttyclock.c:(.text+0xf8): undefined reference to `cbreak'
ttyclock.c:(.text+0xfd): undefined reference to`noecho'
ttyclock.c:(.text+0x104): undefined reference to `stdscr'
ttyclock.c:(.text+0x111): undefined reference to`keypad'
ttyclock.c:(.text+0x116): undefined reference to `start_color'
ttyclock.c:(.text+0x120): undefined reference to`curs_set'
ttyclock.c:(.text+0x127): undefined reference to `stdscr'
ttyclock.c:(.text+0x12f): undefined reference to`wclear'
ttyclock.c:(.text+0x134): undefined reference to `use_default_colors'
ttyclock.c:(.text+0x16a): undefined reference to`init_pair'
ttyclock.c:(.text+0x18e): undefined reference to `init_pair'
ttyclock.c:(.text+0x1b2): undefined reference to`init_pair'
ttyclock.c:(.text+0x1b9): undefined reference to `stdscr'
ttyclock.c:(.text+0x1c1): undefined reference to`wrefresh'
ttyclock.c:(.text+0x399): undefined reference to `newwin'
ttyclock.c:(.text+0x3e9): undefined reference to`wborder'
ttyclock.c:(.text+0x41b): undefined reference to `wattr_on'
ttyclock.c:(.text+0x4ac): undefined reference to`newwin'
ttyclock.c:(.text+0x4fc): undefined reference to `wborder'
ttyclock.c:(.text+0x51b): undefined reference to`clearok'
ttyclock.c:(.text+0x533): undefined reference to `stdscr'
ttyclock.c:(.text+0x540): undefined reference to`nodelay'
ttyclock.c:(.text+0x564): undefined reference to `wrefresh'
ttyclock.c:(.text+0x57a): undefined reference to`wrefresh'
/tmp/ccky1p0y.o: In function `signal_handler':
ttyclock.c:(.text+0x5b6): undefined reference to`endwin'
ttyclock.c:(.text+0x5d1): undefined reference to `endwin'
/tmp/ccky1p0y.o: In function`cleanup':
ttyclock.c:(.text+0x623): undefined reference to `delscreen'
/tmp/ccky1p0y.o: In function`draw_number':
ttyclock.c:(.text+0x9c1): undefined reference to `wattr_on'
ttyclock.c:(.text+0x9e3): undefined reference to`wattr_off'
ttyclock.c:(.text+0xa29): undefined reference to `wbkgdset'
ttyclock.c:(.text+0xa47): undefined reference to`wmove'
ttyclock.c:(.text+0xa67): undefined reference to `waddch'
ttyclock.c:(.text+0xa8f): undefined reference to`wrefresh'
/tmp/ccky1p0y.o: In function `draw_clock':
ttyclock.c:(.text+0xb1f): undefined reference to`wbkgdset'
ttyclock.c:(.text+0xb3f): undefined reference to `wmove'
ttyclock.c:(.text+0xb64): undefined reference to`waddnstr'
ttyclock.c:(.text+0xb84): undefined reference to `wmove'
ttyclock.c:(.text+0xba9): undefined reference to`waddnstr'
ttyclock.c:(.text+0xc13): undefined reference to `wattr_on'
ttyclock.c:(.text+0xc35): undefined reference to`wattr_off'
ttyclock.c:(.text+0xc5e): undefined reference to `wbkgdset'
ttyclock.c:(.text+0xc94): undefined reference to`mvwprintw'
ttyclock.c:(.text+0xcaa): undefined reference to `wrefresh'
ttyclock.c:(.text+0xcd7): undefined reference to`wbkgdset'
ttyclock.c:(.text+0xcf7): undefined reference to `wmove'
ttyclock.c:(.text+0xd1c): undefined reference to`waddnstr'
ttyclock.c:(.text+0xd3c): undefined reference to `wmove'
ttyclock.c:(.text+0xd61): undefined reference to`waddnstr'
/tmp/ccky1p0y.o: In function `clock_move':
ttyclock.c:(.text+0xdd1): undefined reference to`wbkgdset'
ttyclock.c:(.text+0xe0c): undefined reference to `wborder'
ttyclock.c:(.text+0xe26): undefined reference to`werase'
ttyclock.c:(.text+0xe3c): undefined reference to `wrefresh'
ttyclock.c:(.text+0xe69): undefined reference to`wbkgdset'
ttyclock.c:(.text+0xea4): undefined reference to `wborder'
ttyclock.c:(.text+0xebe): undefined reference to`werase'
ttyclock.c:(.text+0xed4): undefined reference to `wrefresh'
ttyclock.c:(.text+0xf0c): undefined reference to`mvwin'
ttyclock.c:(.text+0xf44): undefined reference to `wresize'
ttyclock.c:(.text+0xfcb): undefined reference to`mvwin'
ttyclock.c:(.text+0x1000): undefined reference to `wresize'
ttyclock.c:(.text+0x1049): undefined reference to`wborder'
ttyclock.c:(.text+0x1096): undefined reference to `wborder'
ttyclock.c:(.text+0x10b0): undefined reference to`wrefresh'
ttyclock.c:(.text+0x10c6): undefined reference to `wrefresh'
/tmp/ccky1p0y.o: In function`clock_rebound':
ttyclock.c:(.text+0x1112): undefined reference to `LINES'
ttyclock.c:(.text+0x1167): undefined reference to`COLS'
/tmp/ccky1p0y.o: In function `set_second':
ttyclock.c:(.text+0x123e): undefined reference to`COLS'
/tmp/ccky1p0y.o: In function `set_center':
ttyclock.c:(.text+0x12d0): undefined reference to`COLS'
ttyclock.c:(.text+0x12f8): undefined reference to `LINES'
/tmp/ccky1p0y.o: In function`set_box':
ttyclock.c:(.text+0x135b): undefined reference to `wbkgdset'
ttyclock.c:(.text+0x1376): undefined reference to`wbkgdset'
ttyclock.c:(.text+0x13a3): undefined reference to `wbkgdset'
ttyclock.c:(.text+0x13be): undefined reference to`wbkgdset'
ttyclock.c:(.text+0x13f9): undefined reference to `wborder'
ttyclock.c:(.text+0x1438): undefined reference to`wborder'
ttyclock.c:(.text+0x1479): undefined reference to `wborder'
ttyclock.c:(.text+0x14b8): undefined reference to`wborder'
ttyclock.c:(.text+0x14d2): undefined reference to `wrefresh'
ttyclock.c:(.text+0x14e8): undefined reference to`wrefresh'
/tmp/ccky1p0y.o: In function `key_event':
ttyclock.c:(.text+0x152a): undefined reference to`stdscr'
ttyclock.c:(.text+0x1532): undefined reference to `wgetch'
ttyclock.c:(.text+0x15aa): undefined reference to`init_pair'
ttyclock.c:(.text+0x15c7): undefined reference to `init_pair'
ttyclock.c:(.text+0x15dd): undefined reference to`stdscr'
ttyclock.c:(.text+0x15e5): undefined reference to `wgetch'
ttyclock.c:(.text+0x1670): undefined reference to`LINES'
ttyclock.c:(.text+0x173d): undefined reference to `COLS'
ttyclock.c:(.text+0x1921): undefined reference to`init_pair'
ttyclock.c:(.text+0x193e): undefined reference to `init_pair'
/tmp/ccky1p0y.o: In function`main':
ttyclock.c:(.text+0x1d8d): undefined reference to `stdscr'
ttyclock.c:(.text+0x1d9f): undefined reference to`wattr_on'
ttyclock.c:(.text+0x1dc7): undefined reference to `endwin'
collect2: error: ld returned 1 exit status
Makefile:22: recipe for target 'tty-clock' failed
make: **\* [tty-clock] Error 1

[dave@manjaro tty-clock-master :( ]$

**Comment by bendem** [comment]
You can compile it with `CFLAGS=$(pkg-config --libs ncurses) make`
