### ISSUE TITLE
Date format becomes misaligned when the day changes

### ISSUE THREAD

**Issue by ammongit** [xorg62/tty-clock#35]
After midnight, the date format at the bottom becomes misaligned due to it not taking up the same amount of space any more. I can reliably recreate this bug by waiting until midnight and seeing the format get changed.

The date format I am using is `%A %B %d, %Y`.

Here are some pictures of the bug:
![1454141059](https://cloud.githubusercontent.com/assets/8848022/12991898/53a9fb7e-d0c6-11e5-8420-2a60ceba65be.png)
![1454450886](https://cloud.githubusercontent.com/assets/8848022/12991901/55341d26-d0c6-11e5-9ace-80253dcab202.png)
![1454486413](https://cloud.githubusercontent.com/assets/8848022/12991903/565dbcde-d0c6-11e5-859a-078a7d249de5.png)
![1454746968](https://cloud.githubusercontent.com/assets/8848022/12991904/573c08c2-d0c6-11e5-9256-c52abf0c61fe.png)
![1454843679](https://cloud.githubusercontent.com/assets/8848022/12991905/5812a94a-d0c6-11e5-9076-20031aaa2f65.png)
![1455091243](https://cloud.githubusercontent.com/assets/8848022/12991906/58eb3c6a-d0c6-11e5-9b3d-be3e645f3e4c.png)
![tty-clock-bug](https://cloud.githubusercontent.com/assets/8848022/12991907/59a414ec-d0c6-11e5-98d4-ef14966c81b6.png)

**Comment by livibetter** [comment]
I can not reproduce this bug with 516afbf (2015-03-19, around the time this issue opened) and ncurses 6.0 and exactly 55x10 terminal size, in both xterm and st, using the following command:

```bash
$ ./tty-clock -sxtf '%A %B %d, %Y'  # seconds, box, 12h, date format
```

They are perfectly boxed, perhaps there was something changed in ncurses? Because it was ncurses 5.x.

**Comment by ammongit** [comment]
I was able to reproduce this issue on the _old_ version of tty-clock. I am using ncurses 6.0.
![1484380809](https://cloud.githubusercontent.com/assets/8848022/21953518/8633374a-d9ee-11e6-8e42-be189aa1e6fb.png)


However the build from the latest commit seems to be working fine. If it works again tomorrow night, I will close this issue.

**Comment by livibetter** [comment]
@ammongit are you talking about tag v0.1, I still can't reproduce it (the version doesn't have `-x`, so `-stf`). From that screenshot, you have a wrapper script?

**Comment by ammongit** [comment]
I don't know what git revision it was, it was just the same binary from when I originally filed the bug. I do have a wrapper script, but it just sets the options (mostly randomizing the color).

**Comment by ammongit** [comment]
Since it's an old version I'm not too worried about it. If the problem still appears to be gone next time the clock rolls over, I'll assume the issue got fixed somewhere along the way.

**Comment by anarcat** [comment]
reopen if this still occurs.
