### ISSUE TITLE
cant compile in cygwin

### ISSUE THREAD

**Issue by apathyrecharge** [xorg62/tty-clock#36]
build ttyclock.c
CC   ttyclock.c
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xa7): undefined reference to `newterm'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xea): undefined reference to `set_term'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xf1): undefined reference to `initscr'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xf6): undefined reference to `cbreak'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xfb): undefined reference to `noecho'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x100): undefined reference to `ncwrap_stdscr'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x110): undefined reference to `keypad'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x115): undefined reference to `start_color'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x121): undefined reference to `curs_set'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x126): undefined reference to `ncwrap_stdscr'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x12e): undefined reference to `wclear'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x133): undefined reference to `use_default_colors'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x16b): undefined reference to `init_pair'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x193): undefined reference to `init_pair'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x1bb): undefined reference to `init_pair'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x1c0): undefined reference to `ncwrap_stdscr'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x1c8): undefined reference to `wrefresh'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x379): undefined reference to `newwin'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x3de): undefined reference to `wborder'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x40d): undefined reference to `wattr_on'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x48b): undefined reference to `newwin'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x4f0): undefined reference to `wborder'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x50b): undefined reference to `clearok'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x520): undefined reference to `ncwrap_stdscr'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x530): undefined reference to `nodelay'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x54f): undefined reference to `wrefresh'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x562): undefined reference to `wrefresh'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x596): undefined reference to `endwin'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x5af): undefined reference to `endwin'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x608): undefined reference to `delscreen'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x93f): undefined reference to `wattr_on'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x964): undefined reference to `wattr_off'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x9a1): undefined reference to `wbkgdset'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x9c2): undefined reference to `wmove'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x9e2): undefined reference to `waddch'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xa07): undefined reference to `wrefresh'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xa97): undefined reference to `wbkgdset'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xaba): undefined reference to `wmove'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xae2): undefined reference to `waddnstr'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xb05): undefined reference to `wmove'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xb2d): undefined reference to `waddnstr'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xb9c): undefined reference to `wattr_on'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xbc1): undefined reference to `wattr_off'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xbe8): undefined reference to `wbkgdset'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xc17): undefined reference to `mvwprintw'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xc2a): undefined reference to `wrefresh'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xc54): undefined reference to `wbkgdset'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xc77): undefined reference to `wmove'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xc9f): undefined reference to `waddnstr'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xcc2): undefined reference to `wmove'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xcea): undefined reference to `waddnstr'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xd50): undefined reference to `wbkgdset'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xda3): undefined reference to `wborder'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xdb6): undefined reference to `werase'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xdc9): undefined reference to `wrefresh'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xdf4): undefined reference to `wbkgdset'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xe47): undefined reference to `wborder'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xe5a): undefined reference to `werase'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xe6d): undefined reference to `wrefresh'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xea4): undefined reference to `mvwin'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xedb): undefined reference to `wresize'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xf53): undefined reference to `mvwin'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xf87): undefined reference to `wresize'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0xfe6): undefined reference to `wborder'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x1045): undefined reference to `wborder'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x1058): undefined reference to `wrefresh'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x106b): undefined reference to `wrefresh'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x10af): undefined reference to `ncwrap_LINES'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x10f5): undefined reference to `ncwrap_COLS'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x11c2): undefined reference to `ncwrap_COLS'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x1253): undefined reference to `ncwrap_COLS'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x1278): undefined reference to `ncwrap_LINES'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x12e2): undefined reference to `wbkgdset'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x12fd): undefined reference to `wbkgdset'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x1328): undefined reference to `wbkgdset'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x1343): undefined reference to `wbkgdset'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x1396): undefined reference to `wborder'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x13e9): undefined reference to `wborder'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x1441): undefined reference to `wborder'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x1494): undefined reference to `wborder'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x14a7): undefined reference to `wrefresh'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x14ba): undefined reference to `wrefresh'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x14ef): undefined reference to `ncwrap_stdscr'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x14f7): undefined reference to `wgetch'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x1571): undefined reference to `init_pair'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x1594): undefined reference to `init_pair'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x15a8): undefined reference to `ncwrap_stdscr'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x15b0): undefined reference to `wgetch'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x1637): undefined reference to `ncwrap_LINES'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x1706): undefined reference to `ncwrap_COLS'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x18e3): undefined reference to `init_pair'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x1906): undefined reference to `init_pair'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x1d40): undefined reference to `ncwrap_stdscr'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x1d58): undefined reference to `wattr_on'
/tmp/ccdQcYBA.o:ttyclock.c:(.text+0x1d7e): undefined reference to `endwin'
collect2: error: ld returned 1 exit status
make: *** [Makefile:24: tty-clock] Error 1

**Comment by ammongit** [comment]
Do you have the cygwin ncurses package installed?

**Comment by anarcat** [comment]
make sure you have ncurses and pkg-config installed, and try again with the latest git.
