### ISSUE TITLE
Collaborators

### ISSUE THREAD

**Issue by livibetter** [xorg62/tty-clock#42]
I'd like propose an idea to @xorg62 after seeing a couple of long standing and already resolved issues still left open, also @anarcat seems to be on top of them, and staying through all these years.

@xorg62 would you like to have a co-maintainer/collaborator to help you out? If you would, I am nominating @anarcat.

Disclaimer: I do not know @anarcat or have not read much of the codes.

**Comment by anarcat** [comment]
i'm open to collaboration of course. my main issue right now is the lack of release tags, which I documented in #21. it makes  maintenance of the debian package more difficult...

**Comment by anarcat** [comment]
i just got invited to this project. @xorg62 what am i allowed to do? can i pull those tags in #21? or do whatever? :)

**Comment by xorg62** [comment]
whatever! (:

**Comment by anarcat** [comment]
awesome, thanks.

**Comment by livibetter** [comment]
Yes, mission accomplished and thanks to @xorg62 for taking my proposal. Closing.
