### ISSUE TITLE
Date formatting options (-f)

### ISSUE THREAD

**Issue by earthmeLon** [xorg62/tty-clock#5]
I was wondering if you wouldn't mind editing the --help output to clarify how to change the date formatting.

I have tried a number of different ways, but each time I get a segmentation fault.

Thanks for the great clock :D

**Comment by livibetter** [comment]
This seems like related to #1, if so, this should be closed, too.

**Comment by anarcat** [comment]
the segfault was fixed in #1, and the date format is documented in the manpage (it's `strftime(3)`), i assume this is enough.
