### ISSUE TITLE
New option for time zone

### ISSUE THREAD

**Issue by decibyte** [xorg62/tty-clock#50]
I like how there's already the `-u` option to get the clock to show UTC. How about another option to define a time zone, relative to UTC? E.g. `-z +2:00`, to be able to show CEST even without having the computer clock set to this time zone.

Along with #51, this would allow for awesome World Clock monitors, with multiple clocks showing the time in New York, London, Tokyo, etc. -- or any list of cities relevant for yourself or your business.

**Comment by anarcat** [comment]
this is what the `TZ` environment variable is for. i don't think we should implement an option where there is already a standard environment variable knob.

**Comment by decibyte** [comment]
That is brilliant, @anarcat. Thanks!

**Comment by decibyte** [comment]
Oh, maybe the -h/man should mention this?

**Comment by anarcat** [comment]
sure - the manpage could mention the TZ variable... we could take example on the date manpage and add examples with the variable...
