### ISSUE TITLE
tty-clock is licensed under... what ?

### ISSUE THREAD

**Issue by sogalboogalsky** [xorg62/tty-clock#52]
Hi,
I would like to package tty-clock for openSUSE but couldn't find a LICENCE file or any information about it. tty-clock Debian's package show a "Copyright with condition" in the Copyright file, so what would be the appropriate term to put in my rpm spec file ?
Thank you.

**Comment by anarcat** [comment]
the [ttyclock.c](https://github.com/xorg62/tty-clock/blob/master/ttyclock.c) file has a pretty explicit copyright, which is also verbatim in the [Debian copyright file](https://sources.debian.org/src/tty-clock/2.3-1/debian/copyright/). the license is basically a 3-clause BSD license, from a quick glance, but here's the whole thing... just in case:

```
/*
 *      TTY-CLOCK Main file.
 *      Copyright © 2008 Martin Duquesnoy <xorg62@gmail.com>
 *      All rights reserved.
 *
 *      Redistribution and use in source and binary forms, with or without
 *      modification, are permitted provided that the following conditions are
 *      met:
 *
 *      * Redistributions of source code must retain the above copyright
 *        notice, this list of conditions and the following disclaimer.
 *      * Redistributions in binary form must reproduce the above
 *        copyright notice, this list of conditions and the following disclaimer
 *        in the documentation and/or other materials provided with the
 *        distribution.
 *      * Neither the name of the  nor the names of its
 *        contributors may be used to endorse or promote products derived from
 *        this software without specific prior written permission.
 *
 *      THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *      "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *      LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *      A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *      OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *      SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *      LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *      DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *      THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *      (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *      OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
```

where did you see that the copyright was "with condition"?

**Comment by sogalboogalsky** [comment]
Sorry I didn't make myself clear, by "copyright "with condition"" I meant "copyright" with the following permissions:

> Redistribution and use in source and binary forms, with or without
> modification, are permitted provided that the following conditions are
> met

Thank you anyway, now I know it's a "3-clause BSD license".
Regards,

**Comment by anarcat** [comment]
right... this is an "old format" debian/copyright file... new file formats includes a one-line symbolic description that would have been a little clearer. :)
