### ISSUE TITLE
[Aesthetic issue] Centering the clock in the terminal does not also center date. Version: TTY-Clock 2 devel version

### ISSUE THREAD

**Issue by cabbage928** [xorg62/tty-clock#59]
Plz help it looks so good but that bugs me to no end.

**Comment by cabbage928** [comment]
*Amendment* Centering the clock after previously not centering it will not center the date.

**Comment by anarcat** [comment]
it does here, could you provide a way to reproduce the issue or clarify which version is affected?

**Comment by anarcat** [comment]
On 2018-04-17 12:54:35, cabbage928 wrote:
> *Amendment* Centering the clock after previously not centering it will not center the date.

I still cannot reproduce that.

**Comment by cabbage928** [comment]
I will close the issue, then. as evidenced by the aesthetic tag, it's not a huge deal, and the program works as expected. As you said, in further testing I've actually found it difficult to reproduce myself, even with the same tags. Thanks!
