### ISSUE TITLE
ttyclock: ttyclock.c:50: init: Assertion 'ttyclock->ttyscr != ((void *)0)' failed.

### ISSUE THREAD

**Issue by pugthelouie** [xorg62/tty-clock#60]
Hello! I'm trying to run ttyclock from within a `systemd` service and currently it is erroring with 
```ttyclock: ttyclock.c:50: init: Assertion 'ttyclock->ttyscr != ((void *)0)' failed.``` What can i do to fix this?

My command is: `sudo tty-clock -tnc -C 6 -T /dev/tty6`
I'm using Ubuntu Gnome 16.04

**Comment by anarcat** [comment]
is tty6 valid and writable?

**Comment by pugthelouie** [comment]
Yes.

**Comment by anarcat** [comment]
i can't reproduce this here. can you provide more details on how to reproduce this issue? which version of tty-clock are you using, which OS, device, etc.

thanks!
