### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by 532910** [xorg62/tty-clock#66]
Please add locale support. (weekday name for example)

**Comment by DarthWound** [comment]
The only thing I miss in tty-clock :)

**Comment by 1BertoMR** [comment]
sorry, my english is bad.
for tty-clock detected OS locale 
agree in file
* ttyclock.h
     #include<locale.h>
* ttyclock.c
      init(void){
           setlocale(LC_TIME,””);
          //or forced locale setlocale(LC_TIME,"spanish")
      …
      }

**Comment by anarcat** [comment]
patches welcome, @1BertoMR :)

**Comment by 1BertoMR** [comment]
> patches welcome, @1BertoMR :)

[my capture](https://raw.githubusercontent.com/1BertoMR/imagenes/master/Captura%20de%20pantalla_2019-12-13_16-53-34.png)

**Comment by anarcat** [comment]
hola @1BertoMR - puedes enviar una arreglo para su problema? :) 

i am sorry, my spanish is also very poor, but i would be quite happy to merge your patch if you actually send it as a pull request here. See this documentation for more information:

https://help.github.com/es/github/collaborating-with-issues-and-pull-requests/about-pull-requests

Gracias!

**Comment by MoonCactus** [comment]
Thanks @1BertoMR for the no brainer, I fixed it in my fork: `LANG=fr_FR.utf8 ./tty-clock -f %A`
@anarcat may be you will be interested to merge my branch, it has various functions and cleanups (I can make a somehow heavy-handed pull request). You can check here  https://github.com/xorg62/tty-clock/compare/master...MoonCactus:master
