### ISSUE TITLE
screenshot in the README?

### ISSUE THREAD

**Issue by novelistparty** [xorg62/tty-clock#67]
tty-clock looks nice, so could it have a screenshot?

thanks!

**Comment by anarcat** [comment]
yes, that would be nice.

**Comment by novelistparty** [comment]
maybe a gif of the bouncing? I really like the bouncy feature

**Comment by haojie1** [comment]
![Screenshot from 2020-07-26 21-17-57](https://user-images.githubusercontent.com/46878455/88479966-8e1bad80-cf85-11ea-888b-8520f76173d2.png)
