### ISSUE TITLE
ttyclock - 5x7 MOD

### ISSUE THREAD

**Issue by niky45** [xorg62/tty-clock#7]
it was small for me, so I rewrited it to use a 5x7 matrix for each number, instead of the 3x5 one that it comes with...
http://nikyscripts.svn.sourceforge.net/viewvc/nikyscripts/ttyclock-1.1a_5x7/

also, it's likely that i'll do it even bigger .... say, 7x9 or so. 

PS: sorry for the sourceforge repo, i have there all my little projects, so i first uploaded it there... then i realised it would be better if i share it with the developers.

**Comment by anarcat** [comment]
please provide a patch or pull request so we can review this more easily. sorry for the delay.
