### ISSUE TITLE
[sugestion] Force python3, (and maybe change installation path)

### ISSUE THREAD

**Issue by druskus20** [xorg62/tty-clock#71]
When I try to execute the program using python2 (2.7.16) I get the following error:
  File "./tty-countdown", line 94
    print(center(asciiFormat(t, font), getTermDimensions()), end="")
                                                                ^
SyntaxError: invalid syntax

Since the program can only be executed with python3, I suggest you to force python3 by changing the first line of the script to #!/usr/bin/python3.

Also, I find better to install programs on .local/bin and .local/bin/share, but thats up to personal preference.

**Comment by jwilk** [comment]
> File "./tty-countdown", line 94

I'm confused. I don't see such file in this repository.

**Comment by anarcat** [comment]
that might be misfiled. no idea why i :+1:'d this either.
