### ISSUE TITLE
Question: start with crontab?

### ISSUE THREAD

**Issue by PetersOtto** [xorg62/tty-clock#88]
Hi!

I have a question, hopefully easy to answer to you.

I use an old laptop as internetradio. I have installed ubuntu 20.04 server with autologin. I start the radio with "mpc play 1" in a script started by the crontab (@reboot). That works fine.

However I want start the tty-clock after the radio. I use "tty-clock -s -c" but it do not start. When I start the script by "./script.sh" it works.

Have anyone an idea?

**Comment by Dhruv-Vanjari** [comment]
Can you share your script. btw what do you mean by `it works` when you run the script, does tty-clock work or your radio?

**Comment by PetersOtto** [comment]
Hi,
for my laptop I found an other solution without the tty-clock. However I would use it for my raspberry pi.

I have installed Raspberry Pi OS Lite and use auto login. On the RPi is an 3.5" Screen installed.

tty-clock is installed as well and works when I use the keyboard of the pi.

Now I use `sudo nano /etc/crontab ` and put the following inside:
`@reboot root tty-clock`

After rebooting the pi the tty-clock will not start but it should (or not?)

**Comment by Dhruv-Vanjari** [comment]
Hi,
I did some research. cron runs process in system background. When cron runs `tty-clock` using `crond`, tty-clock does not get a `tty` to display the clock.

Try supplying the `tty` in the script
```
tty-clock -T /dev/tty1
```
When you run tty-clock from the terminal, it knows where to display the clock but not when it is being run in the background. You have to manually supply the `tty` where you want to show the clock

**Comment by Dhruv-Vanjari** [comment]
I found a similar issue with cron #20

**Comment by PetersOtto** [comment]
Hi Dhruv-Vanjari! 
Thank you for your help!

Yesterday I tried to start tty-clock by using `rc.local` and it works.
`sudo nano /etc/rc.local`

However I prefer cron and with the following code it works as well.
`@reboot root sleep 60 && TERM=xterm tty-clock -S -c -T /dev/tty1`

:)
