### ISSUE TITLE
LC_TIME ignored ?

### ISSUE THREAD

**Issue by yichnal** [xorg62/tty-clock#95]
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

$ date
Sat 08 May 2021 04:22:50 AM CEST
$ LC_TIME="fr_FR.UTF-8" date
sam. 08 mai 2021 04:25:13 CEST
$ LC_TIME="fr_FR.UTF-8" tty-clock -f"%A %B"
Output :
Saturday May

**Comment by anarcat** [comment]
could you try the latest git? i believe this was fixed quite recently, in https://github.com/xorg62/tty-clock/pull/91

**Comment by yichnal** [comment]
Works great. It happens the ubuntu repo is not up to date ! Thanks.
